### ISSUE TITLE
导入idea中发生乱码

### ISSUE THREAD

**Issue by lukeewin** [ujcms/ujcms#2]
导入idea中，显示乱码。并且sql文件导入报错。

**Comment by ujcms** [comment]
ujcms用的什么版本？哪个地方显示乱码？

**Comment by lukeewin** [comment]
最新版本，application.yml中的中文乱码，其它文件没有乱码。







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ujcms/ujcms"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月27日(星期天) 晚上9:25
***@***.***&gt;;
抄送:&nbsp;"Luke ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ujcms/ujcms] 导入idea中发生乱码 (Issue #2)





 
ujcms用的什么版本？哪个地方显示乱码？

**Comment by ujcms** [comment]
application.properties里的不是乱码，编辑器里进行相应的设置，就会显示中文。下一版将使用yaml作为配置文件的格式，避免注释里的中文在普通编辑器里无法显示。
