### ISSUE TITLE
arbitrary file upload vulnerability in ujcms v6.0.2

### ISSUE THREAD

**Issue by Le1a** [ujcms/ujcms#4]
Hello, I found that your ujcms v6.0.2 version has an arbitrary file upload vulnerability in the background.
In the background file -> upload file here, we can upload files, I know you have made restrictions on the suffix of the uploaded file name, for example, jsp files are not allowed to be uploaded. But we can bypass the check by capturing the packet and modifying the file name to "1.jsp." (adding a decimal point to the suffix).

1. Try to upload 1.jsp file, but it is blocked
![image](https://github.com/ujcms/ujcms/assets/97610822/f696cf64-d53a-4b4d-b314-749951025320)

2. Use burpsuite to capture the package, modify the file name to "1.jsp." and then change the Content-Type to "image/png" to upload successfully
![image](https://github.com/ujcms/ujcms/assets/97610822/0659efb0-9c20-45d5-a36a-d4d92a3a0fae)
![image](https://github.com/ujcms/ujcms/assets/97610822/bc94ad7a-67fc-4f17-a8e0-1c06f8a65617)

3. Click Browse to download the file, and the suffix of the downloaded file is "jsp" instead of "jsp."
![image](https://github.com/ujcms/ujcms/assets/97610822/68368b56-c83a-4016-861c-c41764da74a4)
![image](https://github.com/ujcms/ujcms/assets/97610822/737c57ff-b41c-403a-a84a-2b4ba8e928f2)

4.Suggestion: Check whether the suffix of the uploaded file name is normal, and prevent the suffix of the malformed symbol like "jsp." from bypassing the security check

**Comment by ujcms** [comment]
Thank you, this problem will be fixed in the next version

**Comment by ujcms** [comment]
Fixed in version 7.0.0
