### ISSUE TITLE
Ujcms v6.0.2 has a sensitive file reading problem

### ISSUE THREAD

**Issue by keecth** [ujcms/ujcms#6]
[Vulnerability description]

Ujcms v6.0.2 has a sensitive file reading problem. When using Tomcat to deploy the project, the background zip package downloads the html directory, and modifying the dir parameter causes the source code and configuration files to be downloaded

[Vulnerability Type]
Sensitive file reading(Information Disclosure)

[Vendor of Product]
https://gitee.com/ujcms/ujcms
https://github.com/ujcms/ujcms
https://www.ujcms.com/

[Affected Product Code Base]
v6.0.2

[Vulnerability proof]

Condition: tomcat deployment project

The dir parameter is allowed to be set to "WEB-INF/", and the names parameter is allowed to be set to "classes", so that the source code and web configuration files can be downloaded directly.(There is no html directory by default, you can create it directly through the function)

![image-20230606124209259](http://img.keecth.cn:55566/img/1686026530_0242b5b93b6720688374450ecb374bea.png)

![image-20230606125908489](http://img.keecth.cn:55566/img/1686027549_d080d2383b2014ed8ead8f0c9e3fe895.png)

![image-20230606130027003](http://img.keecth.cn:55566/img/1686027627_f59968b6577553eb93cfcf42ea2adcd5.png)

[Code Details]

com.ujcms.cms.core.web.backendapi.AbstractWebFileController#downloadZip
The code checks the two parameters "dir" and "names" separately

![image-20230606130152382](http://img.keecth.cn:55566/img/1686027712_9bd08457362b8a7f8a46d98f99f1388b.png)

com.ujcms.cms.core.web.backendapi.AbstractWebFileController#checkId(java.lang.String)
Check whether there is directory traversal, no restrictions on accessible directories

![image-20230606130208683](http://img.keecth.cn:55566/img/1686027729_343a257132df8ce84354caf5583fb114.png)

com.ujcms.cms.core.web.backendapi.AbstractWebFileController#checkName(java.lang.String)Check the file name, when both meet
(1) The file name is empty
(2) The file name contains illegal characters
Accessible directories are not restricted

![image-20230606130903428](http://img.keecth.cn:55566/img/1686028143_72d8455143fcd4f79b3c01e49e95feb9.png)

**Comment by ujcms** [comment]
Fixed in version 7.0.0
